apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podmanager
  template:
      metadata:
        labels:
          app: podmanager
      spec:
        containers:
        - name: podmanager
          image: gcr.io/mimetic-parity-378803/flask_manage_pods:latest
          ports:
          - containerPort: 60
